@startuml LandAdministrationDomainModel
allow_mixing

namespace ladm.party {
    class Party {}
}

namespace ladm.administrative {

    interface RightRestrictionOrResponsibility

    class BasicAdministriveUnit

    RightRestrictionOrResponsibility <|-- BasicAdministriveUnit

    ' CadastralObject "1" *-right- "*" LegalRight
    ' CadastralObject "0" *-- "*" LeaseRight
}

namespace ladm.spatialunit {

    class SpatialUnit

}

ladm.party.Party -right- ladm.administrative.RightRestrictionOrResponsibility
ladm.administrative.BasicAdministriveUnit -right- ladm.spatialunit.SpatialUnit

@enduml