@startuml LandRegistryLegal
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

Container_Boundary(sys1, "Land Registry Legal") {
    Container(cadObj, "Cadastral Object", "The Cadastral object")
    Container(legalRight, "Legal Right", "The legal rights of the object")
    Container(lease, "Lease", "The lease (a.k.a. morgage) on the object")

}

Rel_Right(cadObj, legalRight, "has", "1-*")
Rel(cadObj, lease, "has", "0-*")

@enduml