@startuml LandRegistryLegal
allow_mixing

namespace ladm.legal {

    class CadastralObject {
        String id
        String ref
    }

    class LegalRight {

    }

    class LeaseRight {

    }

    CadastralObject "1" *-right- "*" LegalRight
    CadastralObject "0" *-- "*" LeaseRight
}

namespace ladm.person {
    class Person {}
}

ladm.legal.LegalRight -- ladm.person.Person
ladm.legal.LeaseRight -right- ladm.person.Person

@enduml