@startuml C4_Elements
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(notary, "Notary", "The legal person to sign legal documents")
Person(landRegistrar, "Land Registrar", "The party how collects coordinates of the parcels")
System(ladmLegal, "LADM Legal", "The legal part of the Land Administration")
System(ladmSpatial, "LADM Spatial", "The GEO spatial part of the Land Administration")

Rel(ladmSpatial, ladmLegal, "Parcel")
Rel(notary, ladmLegal, "Deed")
Rel(notary, ladmSpatial, "Deed")
Rel(landRegistrar, ladmSpatial, "Deed")
@enduml