@startuml LADM_Components
allow_mixing

!include ladm-common.puml

!include ladm-source.puml
!include ladm-party.puml
!include ladm-administrative.puml
!include ladm-spatialunit.puml

hide members
hide class
hide enum

ladm.party.Party -- ladm.administrative.RightRestrictionOrResponsibility
ladm.administrative.BasicAdministriveUnit -- ladm.spatialunit.SpatialUnit

@enduml